# Discovery Server Access
eureka:
  instance:
    hostname: product
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP (Tomcat) server port
server:
  port: 8081


