spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uchihaaaa/config-repo.git
        #native:
          #search-locations: classpath:/shared
        bootstrap: true
        clone-on-start: true
  profiles:
    active: native