spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uchihaaaa/commerce-microservices/tree/master/configuration/src/main/resources/shared
        #native:
          #search-locations: classpath:/shared
  profiles:
    active: native