spring:
  application:
    name: configuration-microservice
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
server:
  port: 8001